# Generated by Django 5.2 on 2025-05-13 17:44

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('accountname', models.CharField(max_length=100)),
                ('accountemailid', models.EmailField(max_length=254)),
                ('accountphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('accountpan', models.CharField(max_length=10)),
                ('accountgst', models.CharField(max_length=15)),
                ('accountcreatedate', models.DateField()),
                ('address', models.CharField(default='N/A', max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(default='000000', max_length=10)),
                ('userid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default=None, max_length=30, null=True)),
                ('categories', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asappayapp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('transactionname', models.CharField(max_length=100)),
                ('transactionemailid', models.EmailField(max_length=254)),
                ('transactionphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('transactionamount', models.FloatField()),
                ('transactioncreatedate', models.DateField()),
                ('transactionduedate', models.DateField()),
                ('userid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('dob', models.DateField(default=None, null=True)),
                ('mobile', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='images')),
                ('userid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
