# Generated by Django 5.2 on 2025-05-16 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transactionemailid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transactionname',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transactionphone',
        ),
        migrations.AddField(
            model_name='transaction',
            name='accountid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionamount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='userid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_started', to=settings.AUTH_USER_MODEL),
        ),
    ]
