# Generated by Django 5.2 on 2025-05-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0002_remove_transaction_transactionemailid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accountemailid',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
