# Generated by Django 5.2 on 2025-05-16 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0003_transaction_accountemailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='accountemailid',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accountid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='asappayapp.accounts'),
        ),
    ]
