# Generated by Django 5.2 on 2025-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0004_remove_transaction_accountemailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accountgst',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='accountpan',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='address',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='pincode',
            field=models.CharField(default='000000', max_length=10, null=True),
        ),
    ]
