# Generated by Django 5.2 on 2025-05-17 10:12

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0006_alter_accounts_accountemailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accountpan',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='accountphone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='N/A', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='city',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='country',
            field=django_countries.fields.CountryField(default='N/A', max_length=2, null=True),
        ),
    ]
