# Generated by Django 5.2 on 2025-05-17 10:58

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0008_alter_accounts_accountgst_alter_accounts_accountname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountsc',
            fields=[
                ('accountid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('accountname', models.CharField(max_length=100)),
                ('accountemailid', models.EmailField(max_length=254)),
                ('accountphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('accountpan', models.CharField(max_length=10)),
                ('accountgst', models.CharField(max_length=15)),
                ('accountcreatedate', models.DateField()),
                ('address', models.CharField(default='N/A', max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(default='000000', max_length=10)),
                ('userid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accountid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='asappayapp.accountsc'),
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
