# Generated by Django 5.2 on 2025-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0009_accountsc_alter_transaction_accountid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsc',
            name='accountid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
