# Generated by Django 5.2 on 2025-05-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0011_alter_transaction_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionstatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
