# Generated by Django 5.2 on 2025-05-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0012_transaction_transactionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
