# Generated by Django 5.2 on 2025-05-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asappayapp', '0013_transaction_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoiceno',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
